apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authservice-hpa
  namespace: fasttech-foods
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authservice
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 