apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: fasttech-foods
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/swagger"
    spec:
      containers:
        - name: authservice
          image: leonardodfg12/authservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_CONNECTION_STRING
              value: "mongodb://mongodb:27017"
            - name: MONGO_DATABASE_NAME
              value: "AuthDb"
            - name: JWT_KEY
              value: "MySuperSecureKeyForJWT@2025##TokenOk!"
            - name: JWT_ISSUER
              value: "AuthService"
            - name: JWT_AUDIENCE
              value: "APIsInternas"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: fasttech-foods
spec:
  selector:
    app: authservice
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
