apiVersion: v1
kind: ConfigMap
metadata:
  name: fasttech-config
  namespace: fasttech-foods
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  MONGO_CONNECTION_STRING: "mongodb://mongodb:27017"
  MONGO_DATABASE_NAME: "FastTechFoods"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
  MongoDbSettings__ConnectionString: "mongodb://mongodb:27017"
  MongoDbSettings__DatabaseName: "FastTechFoods"
  JWT_KEY: "MySuperSecureKeyForJWT@2025##TokenOk!"
  JWT_ISSUER: "AuthService"
  JWT_AUDIENCE: "APIsInternas" 