{
 "title": "FastTech Foods Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FastTech Foods Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aspnetcore_http_requests_total{kubernetes_namespace=\"fasttech-foods\"}[1m])) by (app, status_code)",
     "legendFormat": "{{app}} ({{status_code}})"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{kubernetes_namespace=\"fasttech-foods\"}[5m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_working_set_bytes{kubernetes_namespace=\"fasttech-foods\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Active Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"fasttech-foods\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}