{
 "title": "SearchService Dashboard",
 "tags": [
  "searchservice",
  "fasttech-foods"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "SearchService Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(search_requests_total{kubernetes_namespace=\"fasttech-foods\"}[1m])) by (endpoint, status)",
     "legendFormat": "{{endpoint}} ({{status}})"
    }
   ]
  },
  {
   "title": "SearchService Response Time (95th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(search_duration_seconds_bucket{kubernetes_namespace=\"fasttech-foods\"}[5m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}} (95th percentile)"
    }
   ]
  },
  {
   "title": "SearchService HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{kubernetes_namespace=\"fasttech-foods\", app=\"searchservice\"}[1m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "SearchService Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{kubernetes_namespace=\"fasttech-foods\", app=\"searchservice\"}[1m])) / sum(rate(http_request_duration_seconds_count{kubernetes_namespace=\"fasttech-foods\", app=\"searchservice\"}[1m]))",
     "legendFormat": "Average Response Time"
    }
   ]
  }
 ]
}